=== apoorv9008/Cafeteria-Management-System/XMLfiles/foodCategory.dtd
<!ELEMENT foodCategory (Specials,Appetizers,Soup,Salad,Entrees,Desserts,Beverage)>
<!ELEMENT Specials (food+)>
<!ELEMENT Appetizers (food+)>
<!ELEMENT Soup (food+)>
<!ELEMENT Salad (food+)>
<!ELEMENT Entrees (food+)>
<!ELEMENT Desserts (food+)>
<!ELEMENT Beverage (food+)>

<!ELEMENT food (foodName,foodPrice,food1Image,food2Image,foodDescription)>
<!ELEMENT foodName (#PCDATA)>
<!ELEMENT foodPrice (#PCDATA)>
<!ELEMENT food1Image (#PCDATA)>
<!ELEMENT food2Image (#PCDATA)>
<!ELEMENT foodDescription (#PCDATA)>

<!ATTLIST food id ID #REQUIRED>

=== apoorv9008/Cafeteria-Management-System/src/XMLfiles/foodCategory.xml
<?xml version="1.0"?>
 <!DOCTYPE foodCategory SYSTEM "foodCategory.dtd">
<foodCategory>
	<Specials>   
            <food id="a1">
		    <foodName>Beef With Cherry</foodName>
		    <foodPrice>6.50</foodPrice>
		    <food1Image>/images/TodaySpecial/beef1.jpg</food1Image>
                    <food2Image>/images/TodaySpecial/beef2.jpg</food2Image>
		    <foodDescription>Beef With Cherry is a flat cut of beef, usually cut perpendicular to the muscle fibers. They are usually grilled, pan-fried, or broiled. The more tender cuts from the loin and rib are cooked quickly, using dry heat, and served whole. Less tender cuts from the chuck or round are cooked with moist heat or are mechanically tenderized.
		    </foodDescription>
	    </food>
	    <food id="a2">
		      <foodName>Humburger</foodName>
		    <foodPrice>5.50</foodPrice>
		    <food1Image>/images/TodaySpecial/humburger1.jpg</food1Image>
                    <food2Image>/images/TodaySpecial/humburger2.jpg</food2Image>
		    <foodDescription>A hamburger (also called a hamburger sandwich, burger or hamburg) is a sandwich consisting of one or more cooked patties of ground meat (beef, pork, turkey, chicken, etc.) usually placed inside a sliced hamburger bun. Hamburgers are often served with lettuce, bacon, tomato, onion, pickles, cheese and condiments such as mustard, mayonnaise, ketchup and relish.
		    </foodDescription>
	    </food>
	    <food id="a3">
		     <foodName>Pancake Stackers</foodName>
		    <foodPrice>7.00</foodPrice>
		    <food1Image>/images/TodaySpecial/pancake stackers1.jpg</food1Image>
                    <food2Image>/images/TodaySpecial/pancake stackers2.jpg</food2Image>
		    <foodDescription>They consist of: a layer of cheesecake sandwiched between two pancakes, available in strawberry, blueberry, or cinnamon apple, all topped with whipped cream. They will be available a la carte or as part of a combo meal, with eggs, hash browns, plus bacon, porks sausage links, or ham, which will tally up to 1,250 calories -- over twice that of a 540-calorie KFC Double Down. 

		    </foodDescription>
	    </food>
	    <food id="a4">
		      <foodName>Oil Pancake</foodName>
		    <foodPrice>4.50</foodPrice>
		    <food1Image>/images/TodaySpecial/Oil Pancake1.jpg</food1Image>
                    <food2Image>/images/TodaySpecial/Oil Pancake2.jpg</food2Image>
		    <foodDescription>A pancake, also known as a hotcake or flapjack is a flat cake, often thin, flat, and round, prepared from a starch-based batter and cooked on a hot surface such as griddle or frying pan. Pancakes may be served at any time with a variety of toppings or fillings including jam, fruit, syrup, chocolate chips, or meat. They are typically considered to be a breakfast food. 

		    </foodDescription>
	    </food>
	    <food id="a5">
		    <foodName>Barbecue Pizza</foodName>
		    <foodPrice>6.50</foodPrice>
		    <food1Image>/images/TodaySpecial/pizza1.jpg</food1Image>
                    <food2Image>/images/TodaySpecial/pizza2.jpg</food2Image>
		    <foodDescription>Barbecue pizza is made with tasty toppings like natural grilled white meat chicken, cherrywood smoke-flavored barbecue sauce, fire-roasted red onions, caramelized onions, cilantro, and white cheddar and mozzarella cheeses, complemented by a smoky barbecue sauce and our thin stone-fired crust made with whole grains. Made with our signature blend of 7 Whole Grains and Sesame with flaxseed.

		    </foodDescription>
	    </food>
	    <food id="a6">
		    <foodName>Taco</foodName>
		    <foodPrice>5.00</foodPrice>
		    <food1Image>/images/TodaySpecial/taco1.jpg</food1Image>
                    <food2Image>/images/TodaySpecial/taco2.jpg</food2Image>
		    <foodDescription>A taco is a traditional Mexican dish composed of a corn or wheat tortilla folded or rolled around a filling. A taco can be made with a variety of fillings, including beef, pork, chicken, seafood, vegetables and cheese, allowing for great versatility and variety. A taco is generally eaten without utensils and is often accompanied by garnishes such as salsa, avocado or guacamole, cilantro, tomatoes, minced meat, onions and lettuce.
		    </foodDescription>
	    </food>
	</Specials>
        
	<Appetizers>
		 <food id="b1">
		    <foodName>Cheese Balls and Sauce</foodName>
		    <foodPrice>6.00</foodPrice>
		    <food1Image>/images/Appetizers/Cheese Balls and Sauce1.jpg</food1Image>
                    <food2Image>/images/Appetizers/Cheese Balls and Sauce2.jpg</food2Image>
		    <foodDescription>The cheese balls are a mixture of pecan meal, bread crumbs, cheese, and eggs. They are smothered in a tomato sauce, and baked to perfection. The balls have a crispy breadcrumb shell on the outside with soft luscious macaroni, and cheesy sauce that oozes out from the center. The generous dusting of cheese at the end brings it all together in a cheesy, crispy, creamy mouthful that is hard to resist.
		    </foodDescription>
	          </food>
	            <food id="b2">
		    <foodName>Mushroom-Scallop Skewers</foodName>
		    <foodPrice>7.00</foodPrice>
		    <food1Image>/images/Appetizers/Mushroom-Scallop Skewers1.jpg</food1Image>
                    <food2Image>/images/Appetizers/Mushroom-Scallop Skewers2.jpg</food2Image>
		    <foodDescription>Smoky bacon and earthy mushrooms complement tender scallops in an appetizer that's ready in 25 minutes. Ingredients include: orange juice, packed brown sugar, grated orange peel, ground ginger, clove garlic, finely chopped, bay scallops, baby portabella mushrooms, stems removed, packaged precooked bacon, and fresh orange curls if desired.
		    </foodDescription>
	            </food>
	    <food id="b3">
		    <foodName>Cheese Berry</foodName>
		    <foodPrice>6.50</foodPrice>
		    <food1Image>/images/Appetizers/Cheese Berry1.jpg</food1Image>
                    <food2Image>/images/Appetizers/Cheese Berry2.jpg</food2Image>
		    <foodDescription>Use seasonal berries for this refreshing salad, matching tangy goat cheese with sweet berries, roasted red onions, walnuts and tomatoes. Ingredients include: red onion (halved and thinly sliced), canola oil, spring lettuce mix, walnuts (roughly chopped), yellow grape tomatoes (halved), mixed seasonal berries, goat cheese (crumbled), raspberry or sherry vinegar, and lemon juice.

		    </foodDescription>
	    </food>
	    <food id="b4">
		    <foodName>Lollipop</foodName>
		    <foodPrice>6.00</foodPrice>
		    <food1Image>/images/Appetizers/lollipop1.jpg</food1Image>
                    <food2Image>/images/Appetizers/lollipop2.jpg</food2Image>
		    <foodDescription>A lollipop is a type of confectionery consisting mainly of hardened, flavored sucrose with corn syrup mounted on a stick and intended for sucking or licking. Different informal terms are used in different places, including lolly, sucker, sticky-pop, etc.  Lollipops are available in a number of colors and flavors, particularly fruit flavors.
		    </foodDescription>
	    </food>
	    <food id="b5">
		    <foodName>Original Nugget</foodName>
		    <foodPrice>5.50</foodPrice>
		    <food1Image>/images/Appetizers/nugget1.jpg</food1Image>
                    <food2Image>/images/Appetizers/nugget2.jpg</food2Image>
		    <foodDescription>A chicken nugget is a chicken product made from either meat slurry or chicken breasts cut to shape, breaded or battered, then deep-fried or baked. Nuggets are typically fried in vegetable oil, such as coconut oil. We also have launched vegetarian alternatives. We serve Garden McNuggets made of beans and cabbage, and a dish containing nuggets made of falafel.
		    </foodDescription>
	    </food>
	    <food id="b6">
		    <foodName>Pork Carnitas</foodName>
		    <foodPrice>6.50</foodPrice>
		    <food1Image>/images/Appetizers/pork carnitas1.jpg</food1Image>
                    <food2Image>/images/Appetizers/pork carnitas2.jpg</food2Image>
		    <foodDescription>Carnitas is a dish made of braised or roasted and then fried or sauteed pork in Mexican cuisine. Pork carnitas are traditionally made using the heavily marbled, rich 'boston butt' or 'picnic ham' cuts of pork. Carnitas are typically served with chopped coriander leaves (cilantro) and diced onion, salsa, guacamole, tortillas, and refried beans (frijoles refritos).

		    </foodDescription>
	    </food> 
	</Appetizers>
        
	<Soup>
		<food id="c1">
		    <foodName>Basil Cream</foodName>
		    <foodPrice>4.00</foodPrice>
		    <food1Image>/images/Soup/Basil cream1.jpg</food1Image>
                    <food2Image>/images/Soup/Basil cream2.jpg</food2Image>
		    <foodDescription>Chicken in a Basil Cream Sauce combines the simplicity of fried chicken with the powerful flavor of the fresh basil all engulfed in a Parmesan cream sauce. The chicken is fried in oil and placed over pasta after it is golden brown. Pour the delicious sauce over the top and enjoy. Chicken in a Basil Cream has such an amazing taste that it was almost work being sick.
		    </foodDescription>
	    </food>
	    <food id="c2">
		      <foodName>Roasted tomato carrot soup</foodName>
		    <foodPrice>3.00</foodPrice>
		    <food1Image>/images/Soup/Roasted tomato and carrot soup1.jpg</food1Image>
                    <food2Image>/images/Soup/Roasted tomato and carrot soup2.jpg</food2Image>
		    <foodDescription>This thick soup is a nice balance of very slightly sweet and spicy flavours with a faint tang from the orange juice. Ingredients include: onions, tomatoes, big carrots, big red bell pepper (capsicum), orange juice (sweetened), milk, olive oil, garlic paste, cumin powder, garam masala, chilli flakes, and vegetable stock. The vegetables need to oven roasted.

		    </foodDescription>
	    </food>
	    <food id="c3">
		     <foodName>chicken-noodle-soup</foodName>
		    <foodPrice>5.50</foodPrice>
		    <food1Image>/images/Soup/chicken-noodle-soup1.jpg</food1Image>
                    <food2Image>/images/Soup/chicken-noodle-soup2.jpg</food2Image>
